### ISSUE TITLE
data:text/html is not possible as src?

### ISSUE THREAD

**Issue by hanbar** [davidjbradshaw/iframe-resizer-react#12]
Failed to execute 'postMessage' on 'Window': Invalid target origin 'data:text/html,' in a call to 'postMessage'.

**Comment by dannyheard7** [comment]
I am also getting this issue when trying to render a base64 pdf

**Comment by davidjbradshaw** [comment]
You need to use [ViewerJS](http://viewerjs.org/) in the iframe to display the PDF, as you can not attach JS directly to a PDF/
