### ISSUE TITLE
Prop changes in iframe-resizer-react are not respected

### ISSUE THREAD

**Issue by pm0u** [davidjbradshaw/iframe-resizer-react#131]
If any of the event listeners are updated, these are not updated & re-bound to the iframe allowing stale event listeners to be run and preventing new event listeners from being added.

https://github.com/davidjbradshaw/iframe-resizer-react/blob/master/src/index.jsx#L25-L31

This dependency array should include all props for the react iframe resizer

**Comment by pm0u** [comment]
Because our embedded iframe page has a ton of layout shift, I wish to ignore resize events for a time - but because this involves re-binding event listeners this is now impossible.

**Comment by davidjbradshaw** [comment]
You can turn this on and off in the iframe, via the API available there. The underlying library would require a major rewrite to do what you're asking, but I shall add it to the backlog of changes for v5.0.0. Draft details at https://iframe-resizer.com
