### ISSUE TITLE
script loading failed due to mismatch type

### ISSUE THREAD

**Issue by BernardA** [davidjbradshaw/iframe-resizer-react#17]
Using the package in a Gatsby app and getting the error below when attempting to fetch the required external script from CDN.

The use is to view message attachments. The attachments are hosted on the back-end ( Symfony API-Platform).

The attachments are correctly fetched - both PDF and images files - but are shown in a `<iframe>` with only about a 150px height. 

This is the error:

> The resource from “https://raw.githubusercontent.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).

As I understand it, this is caused by a configuration issue on the server side.  See [this SO question](https://stackoverflow.com/questions/40728554/resource-blocked-due-to-mime-type-mismatch-x-content-type-options-nosniff). 

The script is included as follows: 

On Helmet: 
        

> const pdfViewerSrc = 'https://raw.github.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js';

      <Helmet>
         <script src={pdfViewerSrc} />
      </Helmet>

`Helmet` inserts this into the `<head>` of the page as follows:
      

> <script src="https://raw.github.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js" data-react-helmet="true"></script>

The `iframe-resize-react` code on the page:

             

        const src = 'http://localhost/images/message/5e85d47553eb6_exercicio.jpg'

        <IframeResizer
               log
               src={src}
              checkOrigin={[
                  'http://127.0.0.1:8000',
                  'http://127.0.0.1:8001',
                  'http://localhost',
               ]}
              style={{ width: '1px', minWidth: '100%' }}
            />

And the `log` output is: 

 
![Screenshot 2020-04-03 at 09 06 36](https://user-images.githubusercontent.com/9449665/78333915-06033980-758b-11ea-8665-390b051b3ad7.png)

**Comment by davidjbradshaw** [comment]
The raw.github.com site is not a CDN and they block you from using it as such. You should use cdnjs instead.

**Comment by BernardA** [comment]
Could you please provide the full URL. Just replacing raw.github.com with cdnjs.com ends up in a 404.

Also, you may want to update the link you provide at the `Usage` section, or otherwise inform the correct URL in your read.me.
