### ISSUE TITLE
Support for sandbox="" configuration

### ISSUE THREAD

**Issue by bluepeter** [davidjbradshaw/iframe-resizer-react#2]
https://html.com/attributes/iframe-sandbox/

**Comment by bluepeter** [comment]
Looks as though this option is supported after all! (May want to document that.) Nice work on repo!

**Comment by davidjbradshaw** [comment]
Hi thanks, all attributes for the iframe element get passed through, it should be noted however, that setting a couple of the `sandbox` options will break this, as they disable support for `postMessage`.

I'd welcome any suggestion on how to improve the docs

**Comment by bluepeter** [comment]
@davidjbradshaw thanks for that. I did notice that I get an error around `postMessage` but the `iframe` resize still seems to work? See screenshot here, and note the console error, but also the correct sizing of the two side-by-side iframes:

<img width="1923" alt="Screen Shot 2019-09-23 at 8 00 16 AM" src="https://user-images.githubusercontent.com/2158187/65437254-56c5f880-ddd8-11e9-8ae5-dfe441205644.png">

Kinda curious how it is properly working despite `postMessage` not correctly executing?

**Comment by davidjbradshaw** [comment]
You can get that error, if the iFrame is slow to load. As you can not post to it until it loads. Iframe-Resizer will try again when the unload event fires, sadly in chrome their is no way to catch this error message.

So it it is working, you can safely ignore it

**Comment by bluepeter** [comment]
So there's no way to avoid this in Chrome? What's odd is that everything works despite adding ` sandbox="allow-scripts allow-same-origin"` which, as you note, presumably should disable `postMessage`?

**Comment by davidjbradshaw** [comment]
I think it is using the sandbox attribute without one of those to values
that causes problems, what you have should work

**Comment by bluepeter** [comment]
Got it, thanks.
