### ISSUE TITLE
resizer not working 

### ISSUE THREAD

**Issue by BernardA** [davidjbradshaw/iframe-resizer-react#20]
I had previously [this issue](https://github.com/davidjbradshaw/iframe-resizer-react/issues/17), which I fixed by copying the resizing file on my own static folder. 

So, the required external javascript is now available on the page as I can see on the `<head>` and I also checked it is loading properly.
        

> <script src="/js/iframeResizer.contentWindow.min.js" data-react-helmet="true"></script>

That did not fix the resizing issue though. It still shows an `<iframe>` of about 150px height. The content in question is available. I tested both with image and pdf files.

This is the iframe-resizer component:

                         <IframeResizer
                            log
                            src={src}
                            checkOrigin={[
                                'http://127.0.0.1:8000',
                                'http://127.0.0.1:8001',
                                'http://localhost',
                                'http://localhost:8000',
                            ]}
                            style={{ width: '1px', minWidth: '100%' }}
                            heightCalculationMethod="bodyOffset"
                        />

This is the log output: 

![Screenshot 2020-04-06 at 10 47 44](https://user-images.githubusercontent.com/9449665/78540198-136f2c80-77f4-11ea-9a4e-6ef0a8e0f71c.png)

**Comment by wayson** [comment]
I think this plugin is for static site only. It's unable to set the height with dynamic content.

**Comment by BernardA** [comment]
That would be extremely odd. It's called 'resizer' for a reason.

From `read.me`:

> This library is the official React interface for iframe-resizer, which enables the automatic resizing of the height and width of both same and cross domain iFrames to fit their contained content. It provides a range of features to address the most common issues with using iFrames, these include:
> 
> Height and width resizing of the iFrame to content size.

**Comment by wayson** [comment]
@BernardA You can try the example with https://web.flexibuzz.com. It just rendered the height of loading icon and stuck there.

![image](https://user-images.githubusercontent.com/3485960/80278688-c075fe80-873b-11ea-8345-27b7defc000c.png)

**Comment by Timopheym** [comment]
you can disable `autoResize={false}`
and check for iframe content loaded there and send size manually
```window.parentIFrame.size(el.offsetHeight, el.offsetWidth);``` where `el` is wrapper of your elements.

**Comment by BernardA** [comment]
Thanks @Timopheym. I did attempt it as below, but that does not work. It will error on `window.parentIFrame` being undefined.

I also seems to me that, in any case, the container component does not react at all to the actual size of the pdf document being loaded, it being inside the iframe. So I am not sure this would work after all. 

           handleIframeLoad = () => {
                  const wrapper = document.getElementById('pdfWrapper');;
                 window.parentIFrame.size(wrapper.offsetHeight, wrapper.offsetWidth);
           }

                       <div id="pdfWrapper">
                        <IframeResizer
                            log
                            onLoad={this.handleIframeLoad}
                            src={src}
                            autoResize={false}
                            checkOrigin="false"
                            style={{ width: '1px', minWidth: '100%' }}
                        />

**Comment by Timopheym** [comment]
> Thanks @Timopheym. I did attempt it as below, but that does not work. It will error on `window.parentIFrame` being undefined.
> 
> I also seems to me that, in any case, the container component does not react at all to the actual size of the pdf document being loaded, it being inside the iframe. So I am not sure this would work after all.
> 
> ```
>        handleIframeLoad = () => {
>               const wrapper = document.getElementById('pdfWrapper');;
>              window.parentIFrame.size(wrapper.offsetHeight, wrapper.offsetWidth);
>        }
> 
>                    <div id="pdfWrapper">
>                     <IframeResizer
>                         log
>                         onLoad={this.handleIframeLoad}
>                         src={src}
>                         autoResize={false}
>                         checkOrigin="false"
>                         style={{ width: '1px', minWidth: '100%' }}
>                     />
> ```

You got me wrong. You should execute `window.parentIFrame.size` inside of Iframe. And `window.parentIFrame` would be availible only if page loaded in iframe, so you might want to wrap it to `if (window.parentIFrame) {window.parentIFrame.size(...)}`

**Comment by BernardA** [comment]
This does not work. `window.parentIframe` will return `undefined`.
It's the same if I try to access it from Chrome's dev tools console.

**Comment by davidjbradshaw** [comment]
Looking at your log file, you are trying to access 127.0.0.1. The browser adds extra security restrictions on localhost, so try another domain, even if it is just the main IP address of your machine

**Comment by BernardA** [comment]
With the below configuration:

on host https://musing-davinci-538143.netlify.app/

        src='https://ba2pi.com/images/message/5ea6b547607db_puzzles.pdf';
       .....
                    <IframeResizer
                        id="pdfWrapper"
                        // className={styles.iframe}
                        log
                        src={src}
                        checkOrigin="false"
                        style={{ width: '1px', minWidth: '100%' }}
                        heightCalculationMethod="bodyOffset"
                    />

It looks like below. Note the log and `window.parentIframe` is undefined.

![Screenshot 2020-04-28 at 17 05 35](https://user-images.githubusercontent.com/9449665/80509234-6ebab780-8979-11ea-910d-a84406b03378.png)

If I try my interpretation of Timopheym's solution, as below:

      const handleIframeLoad = () => {
        if (window.parentIframe) {
            const wrapper = document.getElementById('pdfWrapper');
            window.parentIFrame.size(wrapper.offsetHeight, wrapper.offsetWidth);
        }
    };

                    <IframeResizer
                        id="pdfWrapper"
                        // className={styles.iframe}
                        onLoad={handleIframeLoad}
                        autoResize={false}
                        log
                        src={src}
                        checkOrigin="false"
                        style={{ width: '1px', minWidth: '100%' }}
                        // heightCalculationMethod="bodyOffset"
                    />

It will actually look very much the same as `window.parentIframe` remains `undefined` and the `onLoad` callback will never be triggered.

![Screenshot 2020-04-28 at 17 52 21](https://user-images.githubusercontent.com/9449665/80509641-fa344880-8979-11ea-89e6-447c549108fb.png)


I can, of course, assume the height of a A4 page and force it on the iframe. It will display very much as expected on the initial load but it will  fail to resize on display orientation change for instance. 

    .iframe {
      width: 1px;
     min-width: 100%;
     height: 11in; 
    @media only screen and (max-width: 760px){
         height: 500px;
     }
  }

**Comment by BernardA** [comment]
Just noticed the below warning on console from above images. Not sure what it means.

![Screenshot 2020-04-28 at 18 08 44](https://user-images.githubusercontent.com/9449665/80510757-74190180-897b-11ea-8bd4-d7410a6d4fca.png)

**Comment by BernardA** [comment]
Sorry, accidentally closed.

**Comment by davidjbradshaw** [comment]
You can not put a pdf directly into an iframe, you need to user viewerJS along side the contentWindow js file from iframe-resizer

**Comment by jamie29w** [comment]
Hey there, the resizer is only working intermittently for me. I was originally using it on a Gatsby v2.19.5 site (live [here](https://flamboyant-lichterman-2e71d8.netlify.app/apply/)).

I've also stripped it down to a [Codesandbox here](https://codesandbox.io/s/recursing-rgb-08h3m?file=/src/App.js).

Sometimes it loads the iframe just fine. Others, it only shows the title of the form and leaves the rest to be scrolled over.

Here's the original plug-n-play code provided for the form by my wife's CRM (using iframe-resizer via CDN), in case this helps too. I couldn't get this to work in React, which led me to using iframe-resizer-react.

```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.14/iframeResizer.min.js"></script><iframe src="https://hello.dubsado.com:443/public/form/view/5e9614f70d72b35f16ed80d9" frameborder="0" style="width:1px; min-width:100%;"></iframe><script type="text/javascript">setTimeout(function(){iFrameResize({checkOrigin: false, heightCalculationMethod: "taggedElement"});}, 30)</script>
```

**Comment by BernardA** [comment]
@davidjbradshaw, no kidding? Well it seems that will not work out as Viewerjs says it's only for self-hosted documents. Any ideas?

**Comment by davidjbradshaw** [comment]
Other than look at PDF.js, not really

**Comment by davidjbradshaw** [comment]
@jamie29w the page in your iframe is going to be doing something weird. Sorry I don't have the time to figure it out for you
