### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by bolonio** [davidjbradshaw/iframe-resizer-react#23]
Will you add typescript support? Thanks :)

**Comment by davidjbradshaw** [comment]
I would except a PR with unit tests if someone would like to make it happen

**Comment by davidjbradshaw** [comment]
This would be a good starting point from @ITjesse 

https://github.com/ITJesse/iframe-resizer-react/blob/master/src/types/iframe-resizer.d.ts

Although i guess it would also need the types that are passed through to the iframe element added to it as well

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
