### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by manetrejo** [davidjbradshaw/iframe-resizer-react#24]
I'm getting the famous 'Invalid hook call' but only when a access directly to a page with the IframeResizer. If I first render other page without the IframeResizer and then go to the one it has, iframe works perfectly as expected.

My configuration:
"react": "^16.13.1"
"react-dom": "^16.13.1"
"iframe-resizer-react": "^1.0.3"

**Comment by davidjbradshaw** [comment]
Did you ever work this out?
