### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided (xxx) does not match the recipient window's origin ('http://localhost:3000').

### ISSUE THREAD

**Issue by superpig** [davidjbradshaw/iframe-resizer-react#25]
I got the following error when i use iframe-resizer-react, although it does not affect function, how can i remove it.

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided (xxx) does not match the recipient window's origin ('http://localhost:3000').

**Comment by davidjbradshaw** [comment]
Use a browser other than Chrome, the problem is the call to the iframe is made before the iframe is loaded and Chrome make this pointless error message. Their is no way to turn it off

**Comment by FedeBev** [comment]
Hi @davidjbradshaw ,

are you saying this library doesn't work on chrome? Because I'm facing the same issue with minimal setup.

Thanks

**Comment by davidjbradshaw** [comment]
No, I am saying the error message is erroneous in Chrome and can be ignored if everything else works

**Comment by Luiz-Not** [comment]
@davidjbradshaw Hi, i test in Safari and get error too.

![image](https://user-images.githubusercontent.com/9080850/154108608-5118b9a0-5372-4c03-9d57-3129adbaa9fc.png)

The error comes from this line on the image, could we add a try catch to avoid ?
