### ISSUE TITLE
ForwardRef and TypeScript

### ISSUE THREAD

**Issue by sicsol** [davidjbradshaw/iframe-resizer-react#38]
I'm getting the following error from TypeScript regarding forwardRef

```Property 'forwardRef' does not exist on type 'IntrinsicAttributes & Pick<DetailedHTMLProps<IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>```

**Comment by pikhovkin** [comment]
The same issue

**Comment by davidjbradshaw** [comment]
Fixed in v1.0.5, sorry for the delay
