### ISSUE TITLE
Iframe height doesn't readjust to the content

### ISSUE THREAD

**Issue by diegoarcega** [davidjbradshaw/iframe-resizer-react#41]
**This is my code:** 

```javascript
 <Route path={'/test'} exact>
        <IframeResizer
          heightCalculationMethod="lowestElement"
          widthCalculationMethod="max"
          src="https://calendly.com/diegoarcega/grcroteau-groups?month=2020-09"
        />
 </Route>
```

**and this is the result:**
![image](https://user-images.githubusercontent.com/1951007/93354840-d7fd7300-f813-11ea-8560-624376fb9b86.png)

**sandbox**
https://codesandbox.io/s/lively-paper-bx7k6?file=/src/App.js

I want the iframe height to always show the whole content within the iframe and never show the scroll. However the iframe element is not resizing at all. 

@davidjbradshaw

**Comment by diegoarcega** [comment]
Do I have to have access to calendly's page and add the` iframeResizer.contentWindow.min.js` script? seems to be the case

**Comment by misraelson** [comment]
@diegoarcega What was the resolution to this?

**Comment by iamisti** [comment]
i'd like to know too @diegoarcega
