### ISSUE TITLE
Any proper example for sendMessage?

### ISSUE THREAD

**Issue by surjithctly** [davidjbradshaw/iframe-resizer-react#52]
Hello,

I'm trying to pass a class name to the child iframe from parent on a `click` event. I know I have to use `sendMessage`. But there is no example provided for:

1. How should we pass sendMessage on a particular event such as click. 
2. Then, what should I include in the child iframe to receive it and make an action based on that. 

Mostly the links redirects to the `iframe-resizer` repo which uses jquery, so it is not useful. 

It would be great if you could provide an example on how this could work? 

Simply: Send a message to child on clicking parent button then show alert on child. 

Any help would be appreciated because I'm lost. 

~Surjith

**Comment by davidjbradshaw** [comment]
Example with the new V5 release

https://iframe-resizer.com/frameworks/react/#advanced-example
