### ISSUE TITLE
[Question] iframe requires height to start, but doesnt change after resize event

### ISSUE THREAD

**Issue by staghouse** [davidjbradshaw/iframe-resizer-react#6]
Hi there, thanks for developing this but I am running either in to trouble getting it to function properly or am missing its functionality.

## Code

```
import React, { useRef } from 'react';
import IframeResizer from 'iframe-resizer-react';

import './sign-up-form.scss';

export default () => {
  const iframeRef = useRef(null);

  const onResized = () => {
    iframeRef.width = iframeRef.contentWindow.document.body.scrollWidth;
    iframeRef.height = iframeRef.contentWindow.document.body.scrollHeight;
  };
  
  return (
    <section
      className="form-wrapper">
      <IframeResizer
        forwardRef={iframeRef}
        onResized={onResized}
        heightCalculationMethod="lowestElement"
        style={{ width: '1px', minWidth: '100%', height: '470px'}}
        src="https://docs.google.com/forms/d/e/1FAIpQLSevsR2ScryvDw6Mto5sP3qImKrQ37nP4cg9zltUeIQfM8_0XA/viewform?embedded=true"
      />
    </section>
  );
};
```

## Functionality

`form-wrapper` provides a container for the form with some padding for nice visual space with no hard coded size (auto height to its children). The iframe loads from Google Forms embed and by standard iframe loading, just loads at 250px height. The form itself works like this: It has a question and when its answered, the iframe gets smaller to let you know its answered. My assumption is that the above code should resize the the iframe smaller and thus the overall `form-wrapper` should get smaller.

## Problem

In order to show the whole iframe, i have to set a height to the iframe but when the resize event fires, the height of the iframe does not change in CSS

## Expectation

Iframe has a set height (as needed), then on the onResize event, the iframe should resize the CSS (thats my assumption)

## Notes

Am I missing come config?

Thank you for your time.

**Comment by davidjbradshaw** [comment]
Have you added the iframeresizer-contentwindow.js file to the remote domain?
