### ISSUE TITLE
Use this library in an iframed CRA?

### ISSUE THREAD

**Issue by DjolePetrovic** [davidjbradshaw/iframe-resizer-react#67]
Hi

Thanks for this package. Really helped me a lot. Just one question. How can I receive messages from a Parent window in my iframed  CRA (create-react-app). 

I was able to send messages from my child to the parent. But not the other way round. And I'm sure it doesn't help that I'm using typescript too. 

Thx

**Comment by davidjbradshaw** [comment]
That should work and I have recently tested in V5.

Here is an example of how I got it to work.

https://iframe-resizer.com/frameworks/react/#advanced-example
