### ISSUE TITLE
How to use srcdoc with the official React wrapper?

### ISSUE THREAD

**Issue by meglio** [davidjbradshaw/iframe-resizer-react#75]
I could not find an example or the API documentation mentioning the use of `srcDoc`.

Please advise whether it's possible to use `srcDoc` attribute with the official React wrapper, and if so, should we expect all functionality, or limited functionality, and what are the caveats.

Many thanks,
-- Anton

**Comment by davidjbradshaw** [comment]
I’ve never tried, I expect it should work as all attributes not used via the api are past to the tag

**Comment by meglio** [comment]
You've never tried, and the API documentation was not improved, but you still closed the issue?

**Comment by davidjbradshaw** [comment]
It's been two years since there was a comment on this issue, I have seen it done by someone else, it works, but it makes debugging issues difficult due to the browser inspector just showing the iframe as a string of data, rather than a page you can inspect. So it is not recommended.
