### ISSUE TITLE
Error when iframe closes

### ISSUE THREAD

**Issue by ymor** [davidjbradshaw/iframe-resizer-react#8]
Hi,
Relating to this issue: https://github.com/davidjbradshaw/iframe-resizer-react/issues/4
The error is still occurring in v1.0.1 and it's quite annoying during development time.
![image](https://user-images.githubusercontent.com/2701844/72798627-65fc6c00-3c3b-11ea-9750-65fb3c9a62e0.png)

This is because it still tries to get 'Id' from 'iframeRef.current' regardless if its null or not for the string interpolation.
Thanks.

**Comment by rossjs** [comment]
Yeah, this is becoming a deal breaker for me. When I navigate to another page (w/ react router) and the component unmounts, this crashes my app every time.

**Comment by davidjbradshaw** [comment]
Happy to take a PR if someone has time to look at this
