### ISSUE TITLE
Leaving the parent page causes an error in React 

### ISSUE THREAD

**Issue by stillnotdavid** [davidjbradshaw/iframe-resizer-react#96]
**Describe the bug**
When navigating away from a parent page with IFrameResizer, the destination page returns this error:

```
Error in function eval in ./node_modules/iframe-resizer-react/dist/index.es.js:1558
Cannot read properties of null (reading 'iFrameResizer')

./node_modules/iframe-resizer-react/dist/index.es.js:1558
Open in Editor
  1556 |     }), iframe);
  1557 |     return function () {
> 1558 |       return iframe.iFrameResizer && iframe.iFrameResizer.removeListeners();
  1559 |     };
  1560 |   }, []); // eslint-disable-line react-hooks/exhaustive-deps
  1561 |
```

Is this a user error on my end or a known issue at all? I'm using v1.1.0 with Gatsby.

**Comment by davidjbradshaw** [comment]
It was a bit of both, looks like the iframe was removed from the page outside of React, but it also should not crash when this happens. Fixed in 1.0.8.
